# Generated by Django 4.1.3 on 2022-12-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spectralImages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="spectralimage", name="mask_image",),
        migrations.AddField(
            model_name="binarymasksimage",
            name="spectral_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="spectralImages.spectralimage",
            ),
        ),
    ]
